"""Add share_bot_inbox table

Revision ID: 10ca6a6aad48
Revises: 390ed4ea9d3e
Create Date: 2026-09-17 12:14:53.156850

"""
from alembic import op
import sqlalchemy as sa


revision = '10ca6a6aad48'
down_revision = '390ed4ea9d3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_bot_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('photo_file_id', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_bot_inbox')
    # ### end Alembic commands ###
