"""add deadline to raw_posts

Revision ID: 390ed4ea9d3e
Revises: cbe693a8c5b2
Create Date: 2026-09-16 16:13:05.673633

"""
from alembic import op
import sqlalchemy as sa


revision = '390ed4ea9d3e'
down_revision = 'cbe693a8c5b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_posts', sa.Column('deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_posts', 'deadline')
    # ### end Alembic commands ###
