"""add posted_date to raw_posts and jobs

Revision ID: cbe693a8c5b2
Revises: df0995fd2c4c
Create Date: 2026-09-16 15:05:51.729150

"""
from alembic import op
import sqlalchemy as sa


revision = 'cbe693a8c5b2'
down_revision = 'df0995fd2c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('posted_date', sa.Date(), nullable=True))
    op.add_column('raw_posts', sa.Column('posted_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_posts', 'posted_date')
    op.drop_column('jobs', 'posted_date')
    # ### end Alembic commands ###
